version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d

  app1:
    image: jwilder/whoami
    container_name: app1

  app2:
    image: jwilder/whoami
    container_name: app2

  oauth2_proxy:
    image: a5huynh/oauth2_proxy
    container_name: oauth_proxy
    command: -config=/etc/oauth2_proxy.cfg
    volumes:
      - ./oauth2_proxy.cfg:/etc/oauth2_proxy.cfg
